### ISSUE TITLE
datasetquery crashes max

### ISSUE THREAD

**Issue by tremblap** [flucoma/flucoma-max#148]
load the included dataset in the included patch

pressing 55 (which has an entry) works

pressing 54 (which has no entry) crashes
[Archive.zip](https://github.com/flucoma/flucoma-max/files/8199082/Archive.zip)

**Comment by weefuzzy** [comment]
This was  a slippery one: 
* if you disconnect the patch chord before the dump and manually click, it's fine 
* if you deferlow, it's fine 
* it'll only crash after a successful query 

Turns out that under these conditions, a stack variable that gets passed into `json_reader` (a cycling thing) wasn't getting cleared on the unsuccessful call.
