### ISSUE TITLE
`fluid.datatset~`s don't resize when given `refer` message

### ISSUE THREAD

**Issue by rconstanzo** [flucoma/flucoma-max#238]
Another one that had me scratching my head for a bit, but it seems if you `refer` a dataset into a new `fluid.dataset~` container, it doesn't resize (downward). This is problematic when chaining together processes where you need to `dump` or `getname` a "virtual" (automatically-named) `fluid.dataset~` at the bottom of a processing chain.

Also, although my patch below doesn't reproduce this error, in the larger patch where I pulled it from it seems to leave garbage data in the "extra" columns when I resize (e.g. I had a whole column of `0.03` in my larger patch when I would resize downward).

![Screenshot 2022-05-30 at 5 45 06 pm](https://user-images.githubusercontent.com/2747015/171034268-d73e11e0-a8c4-4448-bf48-6fd8f4214816.png)

<pre><code>
----------begin_max5_patcher----------
2164.3oc2bssjiZCD8YOeEJtRp7hWB5FWxSIuk+gsR4R1H6gcw.EHOyr6Va9
1iP.1BOfsrGjGOdbUiKKIftOp6V8Q.8OdXxzEYuvKmB9SvmASl7iGlLQ0TUC
SZ98joaXurLgUpF1zkYa1vSESmU2mf+hP0t3QdA+2KAoYOCXo.9lbw2.KyR1
tI0wwoc34E7R4QyDwYoyShS4Ky1lpNAzlQDGoNcYK9xmfgsGV51MwoIbgRDf
6aLaqnsU21q.Sr7w3z0yK3KE0JFJvywcF.Acq9B5ST+R9Cv+VcL+7gGp92r2
H.fc.E7U7BPDSvvRLHBjWDuefqxREqXK45pflxhb0GXY72UCrRJOFFTM1T1F
0Xm9O7jm3h3kromKBQo0Phu5KTM.4Mx.DKIArNKK5Wl1yTcvnNUC8Cq9hZmY
Zj9LM4rmogdu6yzPeOaNSCc.aXekqvmRoLAdNV7H.MCfmoPKRSfgRSQL56Hh
EphZPT.FABeS.VJ+Yo97J7JWAWsnUetGD733eTO8KUIhq9edx1v0VDUZl9wy
KZzmFERhqwI7m3EkxP3Zxvjor7bslmncHUnvWxTmnfY6ZJNstI7tlJ3OEe3o
UddKjZgPpBaKpmKewiLc+oIKhWjtMVcL0MJmOZDIExWYCTl2XcolfZ6VCWTw
KftJ+AHDo.Cu.u8ngbpccR1R4zjFDOYZVNOMNUeYsNcGwWw1lHlqa2BQN81e
qCPuctyP9uKhYI6zf0EwQYoUBQmohplaubeF.q84o5JiZDor7dNXoAmDWFny
RoRtsbAqnZlZQRsiXamhrrjtcs63R3qDMcmGmld.JJxxGtyh30OdjicQlryM
G6bq5ob91z5dmKMJDyKYO0EsEx0mZ7O6d5egkFugIjQO1zD2YWm7TlTQerbY
QVRRG8stmm5omHoQ9R9ywQhGUWHciA4viyaMhltaVNJdMuTzsMAacY2VJEeq
Fz0ZZ6hFm34BYFYIRsn6.jtGwkhxGydtrYfsFZ5.v9LD0cp0C10o8iEz6fjF
AK.KS3rB8dqijI9Vdi46zErz0SmIWtQMxc1vGDiDGneR5KLYOgJQZ8zW3RUr
eOjJYB39.jsGjJ7eSHmKDcjwlJYq48BO5YUzOzLHZfPChFnAQC3wQCeYHDpb
Qbu.Ge2v1OvpUOvHq.NGwz4S.3QQlJjaPvAO9fSfL0.I3fjqvFPI6+3Ky4AE
p55JhNBPLXwIwmYM9VChSjw2kpEmfdNAg5VQTki1UFmx47u9efxXYrQddlDS
PGEzVkjwNhYEcP3B+FMqvRSHeMqJOOrJOkqsW21uGCPFErt86i5G5cA9g3SD
jRlbKshgiuSHxe+GruL8c2qMd8GxbJcccdKFU9VHVUCe+PhS.T6SEDQu1PTg
jQX1FENc4AzCsGH0W.85sW3iW.cLb7Cn66o10HHNvIzCq8IPZMYm.5GKmoSm
N4vniERKvySQor2blt5tZK1tZEun65cf+pjsIuDPLHF0IMurP9B9tJXhf8bz
stBnUK.5GbsgvRUN4q.rnHE9A9sHySeXXfidA.GzH+x9r7fAuKINTEhG3NZY
OfsP1CMtqRIU8E5piSqR1FG4zrUf+mZGTOgM0riYW4as38DWeGOs7qHT+pLR
IenHIO9w6Itg2GbjsvZgTW5cGEYOaroSzaYFx32.YlvwmfbCZcKQPFOZKwAw
i+Rbj.xcEAYHwBQpHg2WDjgT6AR2SDjgVHdNwCdmPPFZg8hBSCtoIHiGSBxP
KbOpvggefHHiuPKuvwmfbie48KAYj63m8Pi65MEAY7kSPFAsV796ABxDuwOf
OzEdmvP1Bae.LzuWJxD5GWJxX2w2GqEmtQ4HSdK7YPiOI4F35VhjLY7HICG+
k4pd.YumHIGL9gpPD38EGYe6gQ8EN+iJEYjE3v.o36DJx9Paru42zLjIiJCY
KjrPH7CDAYxkY2YgafbiS48K+Xx3m2Psq5ME6XxkyNFZsH8WUxwJw9zVMCeC
FFNib22VLcH0IryexPR35n8tZusFpWkkl20J8GeekflFweQ6keoChs+88n5c
sbfmhekzU0e+PYY11hks.Ua91.TGgKhWJhS285u748D+.lNUd1RA1PovylBA
o9jeRgHTNNn0DBjgRQ0qHg8vBpgRQKnYGovqFoOsTfssTXDVDZSov2PonZWP
smTDdKHEnaBgv0vXVPOaKEl3hfroPXbLKeaJEXSMKn1TJLcUDD11RgQlE1Ll
U0qDhQtHHatJBx+brKr0B6U6zhYqkY0fVAFhEV0Ew3EQrY3B7Yjsm0jAWSCb
hrsTXhooUmNflFwxy1RgQSH1zAAa55oPqZVfuEVUGSuIjBSYhfP1VJLhrtMW
CAa7JYuZlKqHptDjfrmjYzBKtCKZv2WPCAeWDMi7v7FVzbeeQMr+6hnYBpQt
1dADSS51lafjo7OH1b0bhw6biEEB5MfLX79nQsrPXTXFKJClREzltF9va.Kh
fyICy94D2zXaA5ZZUQXJZdcAmZNSHJhWrUTeeJzjlyqvHsNIaAK4fpYTe0Mo
G1KbmYYbSJjBonznDG+tI04IgaWAsLmUHkLAuXdcghRursYPEdCdpJ7Vc4pq
o79QtvpUW2GQh9e7HNxsnt66ehauEvNz4pdUOQVpaOV8cI6fm+gQRA6TMGMU
AgijBhCzUPjUTP8WqXSUPBcjTvlmNr55oENzZJH9bUPxHoftt0OCu1VAImmB
RBFG8idEl+pqup+J77zP7XpfMdfT22jBNPE+r6yowvZ4rgLVOixAJ5jZJQ8L
YDzulpt7ce9ApU7CyenQ8eMsmN6c6f2TXsb3dEFa5kRsLyouVixUBdstRDpA
WoQA8HjqzUhDbktP3KZRp1j+f5Ya0k3f5X6A0v1WW+ZGt10dXcqUkR7P0q1G
94C+Ocz.As.
-----------end_max5_patcher-----------
</code></pre>

**Comment by rconstanzo** [comment]
Also, this state persists even after `clear`-ing the `fluid.dataset~`.

**Comment by weefuzzy** [comment]
I don't understand. The datasets in your patch are all 1000 x 4 when you make them, because the buffers you fill with points are 4 samples long. There's no resizing involved in this, fwiw: `refer` literally just points the max object (basically an empty shell) to a different dataset in memory. If nothing else is referring to the original pointee when this happens, it gets destroyed. 

This seems to work fine: 

<pre><code>
----------begin_max5_patcher----------
2145.3oc4bs0bhaCE9YxuBUl1ouvRst4K8o125+gc5vXvBhaM1drEIY2Ns+1
qrrMHSrMBQDgPVlYYhjv967ctnywWN+yCSltL6EV4TvuB9JXxj+4gISjCUMv
jl+dxzsgurJIrTtroqx1tkkxmNqdNN6Etbb9irB1OWBRydFDlBXay4eCrJKY
21z4ym2t73H4hyV9WeAFzNX5tswoILt7D.aFLOju5w3zMKJXq30.D46N2YF.
Acp9B5Qj+k3O.+4giT1Nd6gxoZv+8gGp9uYWn3gmCJXqYEfnPdHVHgQf7h3C
KbcVJec3JlpHnHrHG0EVF+c4Bqv9XbP0ZSC2JW6z+fk7DiGuJb5vLDkVSIdx
uP0Dj6UgfBSR.axxh9g9T09FppgdAUeQulZZjpllb1ZZn6UTSC8bu9ZZ3bv1
v+lI4mRwwG7bL+Q.ZF.OSxVjF29RcYL5UgwBjQMHRBi.gVfvRYOKjmWwW4R5
pks5y8ffOW+iZ0uPjHNp+yULFt1hXXIS8nxJZjmFARvqwIrmXEkwYoJXXxzv
7bkgmn7SpXg+JSdf7msen3z5gv6Gpf8Tb6u2Y+ngEBYiKDrcE05xWbISObXx
hXEo6hkPodPg9nARRluxFnLuw5RpfZm9.agwHo2BRFWDBQRNx0WQ8KzsaRxV
IzSpvaZVNKMNMufUJ7DB4Gg9oQr0g6R3KTMbgn48NeqGPuSt2R92KhCS1KBa
JhixRq.QGcQ0vsmtuBf0gBnpBibEog487iEVbBhYfIKEB4txkgEUppkI0dhs
SxyxR5N09eWBaMuY573zziXQdV9vSVDu4wQ9sKyDStcrisblxE6Rqmcgvpfu
nL7otrMWrAUiCZ2C+KgowaC4hvGaaB7reRVZnPPerbUQVRRG4sdlm5YlHgU9
J1ywQ7GkmHUiAwxiyaMhltWKGEugUx6NFObSY2QJ4eqlzUFZ2xFu3EbQBWIB
on6BD9Gwk7xGydtrYgsFZpDvgD.U8pUi10Y7wh5cTNgfkfUIrvB0YqCEw+Vd
i46zkgoalNSreibk6sgOJHI1W8fzWbxAiUJC76JCAPgGGcrmHjn1Ijw+ah4X
H6HBNUFtg0K8nlVQ+TyfrABMHafFmM7DAJnh8pc8m64Dz9AVs0QcTxSPNv2P
xYDSmu.fixLUL2fjC1TxwWjWffbPhsW8ojCe7Do1fBjScSvNbPLX4I4mYM9V
CxSDScoZ4In6b+.UqHpzQidUcwFgmxYr+9+.kwhXir7LAmfFkzVmjENhYEcP
5BqEcgElPdJVUttXY1H2Ndc69dL.oUv51uG0Oz03fThLaoUk23MO.4c3C1Sj
6tiF7E95vW+B.Jx5d9kXT4Ybrplh8CHy8gJepnH5siIUgnjvrsRdx7.5AWJI
0W.85qsv8T.cLzz.5dt0kFg8mG3hU93Krlt1AzGKmoSmN4vriwoE35Ju9J8l
yzMjq1xcqWyJ5teG32JC2lWBzYiuSZdYb9BdNRZhfcmqZc4Sq1.zy+JmS9HT
XoLm70fvnHI+A9oH8SeXXhidg9k8Y4A8uwRbnJDOv4MK6Ar6E5tJvS8U8Ac6
jvv5jcwQyatVf+m7RndBapYiYW4cg1UDGu4tJ4WQndUYjRtSJR1TCHhSv8dM
xFuWH0g9IpDYWyunSzOlUHiufhYBLs.4F15iQAx32rs3fF6ER7IeRJPFRLNR
EI3yRAxP5kRReNJPFZb7bhK7tu.YnwWKJL0+CZAx31BjwuAEHCM9dTgCBtKJ
PFankWvE5W9Yr.YjyE5t9Ao.Yr4EHifWnc08cAxDiuDKPG3ceExFe4CfAd8V
hLgdOVhL1wTerVd5CWMxjKodFjoEI2PWeLJRl71UjLzX+PO2OIEI6aJEgHvO
K0H6cobTegyu+JQFYbMLPJ9tuDYOn4W27OnUHSZqPl7VTgrwIKD.uKJPlXlc
G8BcJ+LVeL4xbU+fTcLw7pigWnQ0MRwwRXeZqlguACCmQtiVFJz4Ac9mHjDt
NZuy3tVJyz9xVo936KAZZD6kg7CO79djDmNzSwuD2Uy2OUVlsqXUKQ0jKInK
piXk73z8u8Ke8PgL.H3O0RSdtfnZeV8PQ85rCHzDC9VDCtZhArkw.TGcA0hf
fdCXPPbuE.glZiVvZMPfz.DHa5af0MTE4UqKqHp9UeDYOjoiRB6MLzbdeIMr
66Bzzg0PvggF78k0ptoLuCPCpePoqnWfqlQIv1LdIV2supdm5rGJzc+q1HB1
AE3aBTfNmTLsFJzMESL01nPKqSatcd08vQKT3YaPnkBwplEZBh.KhATft61X
S8AR287n1FDZs6lM2CAoaofUuinVqnXjt6mhH1jKzs.DTfsQgVZDaVYLBeN1
EVCEnagc0Q5tGBx1fPGWDnM2NUW8AxlwrfA2Dnv6l.EZegaBrMJzZuLaFyBp
8URyl6hHup65Ezx2pv3LR2yV6qKU25Dzxlwrj4OoUw5NChhlAa6PWSqZBSQK
pa3TKB47h3k6302mBE3bdMFoMIYKCSNpaF0WeS5gCf6L6iaBPxEPoQHF+tI0
4IgK3P6mqPfLNqXQcihRsuqcds3s59UWS+8iLXScCZfX18Qjn+GOhQtE0ce+
Sb5sC1gFV7pdprj2hr56TF8Dcst2RArS6bTWADd1BH1WU.QWQAT80JVWAjPO
aAr4IDqtmZgCtxBH9bEPxYKfNN0OGuuOBH47DPh+4Jez2M8WcCV8GgmmDhMS
.a7.oNVP.Gnke184zXXob1PFql0OPwD4ykg+ojTjhjJWR2mefZA+3DHZD+wu
fYm99g9JBV2yCwWiSD9M3DIiTbkNSzq0YhBuRpIYp.WkyDNPmSD40zWsI+QM
z1pyxQMx1iZhsutA1Nbyq83FWqLk3gZXsO7uO7+vKJk+q
-----------end_max5_patcher-----------
</code></pre>

**Comment by rconstanzo** [comment]
Duh, my bad!

Was just copy/paste-ing the code in my patch and missed that.
